package org.ampathkenya.utils.sqlgenerator;

import junit.framework.TestCase;
import org.ampathkenya.utils.configparser.TableConfig;

import java.util.Properties;

public class SQLGeneratorTest extends TestCase {

    private SQLGenerator sqlGenerator ;
    private String csvFileContent = "id,firstName,secondName\n" +
            "1,\"First\",\"User\"\n" +
            "2,\"Second\",\"User\"\n" +
            "3,\"Third\",\"User\"\n" +
            "4,\"Fourth\",\"User\"" ;

    private String tableName = "table1" ;
    private Properties properties = new Properties() ;

    private TableConfig tableConfig ;
    protected void setUp() {
        properties.setProperty("id", "int auto_increment") ;
        properties.setProperty("firstName", "varchar(255") ;
        properties.setProperty("secondName", "varchar(255") ;

        tableConfig = new TableConfig(tableName, properties) ;
        sqlGenerator = new SQLGenerator(csvFileContent, tableConfig) ;
    }

    protected void tearDown() {

    }

    protected void testThatCSVConfigOptionsAreDisplayed() {
        String expectedDisplayedConfigs = "Converting 'table1' with configs\n" +
                "id=int auto_increment\n" +
                "firstName=varchar(255)\n" +
                "secondName=varchar(255)\n" +
                "primarykey=id\n" +
                "foreignkey=id REFERENCES shoes.owner_id" ;

        assertEquals("Test that correct set of configs are displayed",
                expectedDisplayedConfigs, sqlGenerator.displayTableConfig());

    }

    protected void testThatSQLDumpFileIsGenerated() {

        final String SQL_HEADER = "-- MySQL dump 10.13, generated by CQSToSQLConverter\n" +
                "--\n" +
                "-- Host: localhost    Database: test\n" +
                "-- ------------------------------------------------------\n" +
                "-- Supported Server version       5.5.34-0ubuntu0.13.04.1\n" +
                "\n" +
                "/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n" +
                "/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n" +
                "/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n" +
                "/*!40101 SET NAMES utf8 */;\n" +
                "/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;\n" +
                "/*!40103 SET TIME_ZONE='+00:00' */;\n" +
                "/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;\n" +
                "/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;\n" +
                "/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n" +
                "/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;\n" +
                "\n"  ;

        final String DML_Statement = "--\n" +
                "-- Table structure for table `table1`\n" +
                "--\n" +
                "/*!40101 SET @saved_cs_client     = @@character_set_client */;\n" +
                "/*!40101 SET character_set_client = utf8 */;\n" +
                "CREATE TABLE `table1` (\n" +
                "id int auto_increment\n" +
                "firstName varchar(255)\n" +
                "lastname varchar(255)\n" +
                "PRIMARY KEY('id')\n" +
                "FOREIGN KEY id REFERENCES shoes.owner.id\n" +
                ") ENGINE=InnoDB DEFAULT CHARSET=latin1;\n" +
                "/*!40101 SET character_set_client = @saved_cs_client */;\n" ;

        final String DDL_Statement = "--\n" +
                "-- Dumping data for table table1`\n" +
                "--\n" +
                "\n" +
                "LOCK TABLES `test1` WRITE;\n" +
                "/*!40000 ALTER TABLE `table1` DISABLE KEYS */;\n" +
                "INSERT INTO table1 VALUES (1,\"First\",\"User\");\n" +
                "INSERT INTO table1 VALUES (1,\"Second\",\"User\");\n" +
                "INSERT INTO table1 VALUES (1,\"Third\",\"User\");\n" +
                "INSERT INTO table1 VALUES (1,\"Fourth\",\"User\");\n" +
                "/*!40000 ALTER TABLE `table1` ENABLE KEYS */;\n" +
                "UNLOCK TABLES;\n" +
                "/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;\n" ;

        final String SQL_FOOTER = "/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;\n" +
                "/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;\n" +
                "/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;\n" +
                "/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;\n" +
                "/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n" +
                "/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n" +
                "/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;\n" ;

        String expectedSQLFile = SQL_HEADER +
                                    DML_Statement +
                                    DDL_Statement +
                                    SQL_FOOTER ;

        assertEquals("Test that correct sql file is generated",
                expectedSQLFile, sqlGenerator.generateSQL());
    }
}
